# Generated by Django 5.0.6 on 2024-06-10 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.IntegerField(default=50)),
                ('for_user', models.CharField(default='ClothOwner', max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.CharField(max_length=500)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://th.bing.com/th/id/OIP.rg_dE8HiSUNjMwZHNHz_8AHaHa?rs=1&pid=ImgDetMain', max_length=1000)),
                ('featured_product', models.BooleanField(default=False)),
                ('com_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clothes.category')),
            ],
        ),
    ]
